import json

nb = {
 "cells": [
  {"cell_type": "markdown", "metadata": {"tags": []}, "source": [
    "# Analisis Dataset Stunting\n",
    "\n",
    "**Proyek:** Prediksi Stunting pada Balita\n",
    "**Dataset:** stunting.csv\n",
    "**Deskripsi:** Dataset berisi data tinggi badan balita berdasarkan umur (bulan) dan jenis kelamin, dengan status stunting (Normal / Stunted / Severely Stunted).\n",
    "\n",
    "---\n",
    "## Tahapan Analisis\n",
    "1. **Setup & Data Loading** - Load dataset dan eksplorasi awal\n",
    "2. **Data Preprocessing** - Pembersihan data, fixing inkonsistensi\n",
    "3. **Handling Missing Values** - Deteksi dan penanganan nilai hilang\n",
    "4. **Outlier Detection & Handling** - Deteksi dan penanganan outlier\n",
    "5. **Export Clean Dataset** - Simpan dataset bersih dan ringkasan\n",
    "---"
  ]},
  {"cell_type": "markdown", "metadata": {"tags": []}, "source": [
    "---\n",
    "# BAGIAN 1: SETUP & DATA LOADING\n",
    "---"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# ============================================================\n",
    "# BAGIAN 1: SETUP & DATA LOADING\n",
    "# Tujuan: Import library, load dataset, dan eksplorasi awal\n",
    "# ============================================================\n",
    "\n",
    "# 1.1 Import Library\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import os\n",
    "import warnings\n",
    "\n",
    "# Buat folder processed jika belum ada\n",
    "os.makedirs('../data/processed', exist_ok=True)\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# Konfigurasi visualisasi\n",
    "plt.rcParams['figure.figsize'] = (10, 6)\n",
    "plt.rcParams['font.size'] = 12\n",
    "sns.set_style('whitegrid')\n",
    "\n",
    "print(\"Library berhasil diimport.\")"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 1.2 Load Dataset\n",
    "df_raw = pd.read_csv('../data/raw/stunting.csv', sep=';')\n",
    "\n",
    "print(f\"Dataset berhasil dimuat!\")\n",
    "print(f\"Shape: {df_raw.shape[0]} baris, {df_raw.shape[1]} kolom\")"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 1.3 Eksplorasi Awal\n",
    "print(\"=== 5 Data Pertama ===\")\n",
    "display(df_raw.head())\n",
    "\n",
    "print(\"\\n=== Informasi Dataset ===\")\n",
    "df_raw.info()\n",
    "\n",
    "print(\"\\n=== Statistik Deskriptif ===\")\n",
    "display(df_raw.describe())"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 1.4 Distribusi Target (Status)\n",
    "print(\"=== Distribusi Status Stunting ===\")\n",
    "status_counts = df_raw['Status'].value_counts()\n",
    "print(status_counts)\n",
    "print(f\"\\nPersentase:\")\n",
    "print(df_raw['Status'].value_counts(normalize=True).mul(100).round(2))\n",
    "\n",
    "# Visualisasi\n",
    "fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n",
    "\n",
    "status_counts.plot(kind='bar', ax=axes[0], color=['green', 'orange', 'red'])\n",
    "axes[0].set_title('Distribusi Status Stunting')\n",
    "axes[0].set_xlabel('Status')\n",
    "axes[0].set_ylabel('Jumlah')\n",
    "axes[0].tick_params(axis='x', rotation=0)\n",
    "\n",
    "status_counts.plot(kind='pie', ax=axes[1], autopct='%1.1f%%',\n",
    "                   colors=['green', 'orange', 'red'], startangle=90)\n",
    "axes[1].set_title('Proporsi Status Stunting')\n",
    "axes[1].set_ylabel('')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('../data/processed/distribusi_status_awal.png', dpi=100, bbox_inches='tight')\n",
    "plt.show()\n",
    "print(\"\\nVisualisasi tersimpan: data/processed/distribusi_status_awal.png\")"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 1.5 Export CSV - Data Awal & Statistik\n",
    "# Simpan data mentah untuk referensi\n",
    "df_raw.to_csv('../data/processed/stunting_00_raw.csv', index=False)\n",
    "print(\"Raw data exported: data/processed/stunting_00_raw.csv\")\n",
    "\n",
    "# Simpan ringkasan statistik\n",
    "summary_stats = df_raw.describe(include='all').round(2)\n",
    "summary_stats.to_csv('../data/processed/stunting_00_summary_stats.csv')\n",
    "print(\"Summary stats exported: data/processed/stunting_00_summary_stats.csv\")\n",
    "\n",
    "# Simpan distribusi status\n",
    "dist_status = df_raw['Status'].value_counts().reset_index()\n",
    "dist_status.columns = ['Status', 'Jumlah']\n",
    "dist_status['Persentase'] = (dist_status['Jumlah'] / dist_status['Jumlah'].sum() * 100).round(2)\n",
    "dist_status.to_csv('../data/processed/stunting_00_distribusi_status.csv', index=False)\n",
    "print(\"Distribusi status exported: data/processed/stunting_00_distribusi_status.csv\")\n",
    "\n",
    "print(f\"\\nTotal {df_raw.shape[0]} sampel, {df_raw.shape[1]} kolom siap diproses.\")"
  ]},
  {"cell_type": "markdown", "metadata": {"tags": []}, "source": [
    "> **Kesimpulan Bagian 1:** Dataset berhasil dimuat. Terlihat ada 1.351 sampel dengan 4 kolom. Distribusi status menunjukkan ketidakseimbangan kelas (class imbalance) dengan mayoritas Normal.\n",
    "\n",
    "---\n",
    "# BAGIAN 2: DATA PREPROCESSING\n",
    "---"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# ============================================================\n",
    "# BAGIAN 2: DATA PREPROCESSING\n",
    "# Tujuan: Membersihkan dataset dari inkonsistensi\n",
    "# ============================================================\n",
    "\n",
    "# Buat salinan untuk preprocessing\n",
    "df = df_raw.copy()\n",
    "\n",
    "# 2.1 Standardisasi Nama Kolom (lowercase, tanpa spasi)\n",
    "df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')\n",
    "print(\"Nama kolom setelah standardisasi:\")\n",
    "print(df.columns.tolist())"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 2.2 Cek dan Fix Inkonsistensi String\n",
    "print(\"=== Nilai Unik di Kolom 'status' SEBELUM pembersihan ===\")\n",
    "print(df['status'].unique())\n",
    "print(df['status'].value_counts())\n",
    "\n",
    "# Fix: hapus spasi berlebih, standardisasi kapitalisasi\n",
    "df['status'] = df['status'].str.strip().str.title()\n",
    "\n",
    "print(\"\\n=== Nilai Unik di Kolom 'status' SETELAH pembersihan ===\")\n",
    "print(df['status'].unique())\n",
    "print(df['status'].value_counts())"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 2.3 Standardisasi Kolom 'jk' (Jenis Kelamin)\n",
    "print(\"=== Nilai Unik di Kolom 'jk' SEBELUM ===\")\n",
    "print(df['jk'].unique())\n",
    "print(df['jk'].value_counts())\n",
    "\n",
    "# Standardisasi: L -> Laki-Laki, P -> Perempuan\n",
    "jk_mapping = {'L': 'Laki-Laki', 'P': 'Perempuan'}\n",
    "df['jk'] = df['jk'].str.strip().map(jk_mapping)\n",
    "\n",
    "print(\"\\n=== Nilai Unik di Kolom 'jk' SETELAH ===\")\n",
    "print(df['jk'].unique())\n",
    "print(df['jk'].value_counts())"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 2.4 Deteksi Duplikasi Data\n",
    "print(\"=== Deteksi Duplikasi Data ===\")\n",
    "duplicates = df.duplicated().sum()\n",
    "print(f\"Jumlah data duplikat: {duplicates}\")\n",
    "\n",
    "if duplicates > 0:\n",
    "    print(\"\\nBaris duplikat:\")\n",
    "    display(df[df.duplicated(keep=False)].sort_values(by=list(df.columns)).head(10))\n",
    "    # Hapus duplikat\n",
    "    df = df.drop_duplicates().reset_index(drop=True)\n",
    "    print(f\"\\n{duplicates} duplikat telah dihapus.\")\n",
    "    print(f\"Shape setelah hapus duplikat: {df.shape}\")\n",
    "else:\n",
    "    print(\"Tidak ada data duplikat.\")"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 2.5 Cek dan Konversi Tipe Data\n",
    "print(\"=== Tipe Data Sebelum Konversi ===\")\n",
    "print(df.dtypes)\n",
    "\n",
    "# Konversi umur_bulan dan tinggi ke numerik (jika ada yang object)\n",
    "df['umur_bulan'] = pd.to_numeric(df['umur_bulan'], errors='coerce')\n",
    "df['tinggi'] = pd.to_numeric(df['tinggi'], errors='coerce')\n",
    "\n",
    "print(\"\\n=== Tipe Data Setelah Konversi ===\")\n",
    "print(df.dtypes)\n",
    "\n",
    "print(\"\\n=== Ringkasan Setelah Preprocessing ===\")\n",
    "display(df.head())\n",
    "print(f\"Shape: {df.shape}\")"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 2.6 Export Intermediate CSV - Hasil Preprocessing\n",
    "df.to_csv('../data/processed/stunting_01_preprocessed.csv', index=False)\n",
    "print(\"Data preprocessing selesai!\")\n",
    "print(f\"Intermediate CSV tersimpan: data/processed/stunting_01_preprocessed.csv\")\n",
    "print(f\"Shape: {df.shape[0]} baris, {df.shape[1]} kolom\")"
  ]},
  {"cell_type": "markdown", "metadata": {"tags": []}, "source": [
    "> **Kesimpulan Bagian 2:** Data preprocessing selesai. Inkonsistensi string telah diperbaiki (spasi pada \"Stunted\", standardisasi kolom 'jk'). Tipe data sudah sesuai.\n",
    "\n",
    "---\n",
    "# BAGIAN 3: HANDLING MISSING VALUES\n",
    "---"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# ============================================================\n",
    "# BAGIAN 3: HANDLING MISSING VALUES\n",
    "# Tujuan: Deteksi dan penanganan missing values\n",
    "# ============================================================\n",
    "\n",
    "# 3.1 Deteksi Missing Values\n",
    "print(\"=== Jumlah Missing Values per Kolom ===\")\n",
    "missing = df.isnull().sum()\n",
    "missing_pct = (df.isnull().sum() / len(df)) * 100\n",
    "missing_df = pd.DataFrame({'Jumlah Missing': missing, 'Persentase (%)': missing_pct.round(2)})\n",
    "print(missing_df[missing_df['Jumlah Missing'] > 0] if missing.sum() > 0 else \"Tidak ada missing values!\")\n",
    "\n",
    "print(f\"\\nTotal missing values: {df.isnull().sum().sum()}\")"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 3.2 Visualisasi Missing Values\n",
    "if df.isnull().sum().sum() > 0:\n",
    "    plt.figure(figsize=(8, 4))\n",
    "    sns.heatmap(df.isnull(), cbar=False, cmap='viridis', yticklabels=False)\n",
    "    plt.title('Peta Missing Values')\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "else:\n",
    "    print(\"Tidak ada missing values untuk divisualisasikan. Dataset sudah bersih dari nilai hilang.\")"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 3.3 Penanganan Missing Values (Jika Ada)\n",
    "total_missing = df.isnull().sum().sum()\n",
    "\n",
    "if total_missing > 0:\n",
    "    # Strategi:\n",
    "    # - Kolom numerik (umur_bulan, tinggi): isi dengan median\n",
    "    # - Kolom kategorikal (jk, status): isi dengan modus\n",
    "\n",
    "    for col in df.columns:\n",
    "        missing_count = df[col].isnull().sum()\n",
    "        if missing_count > 0:\n",
    "            if df[col].dtype in ['float64', 'int64']:\n",
    "                median_val = df[col].median()\n",
    "                df[col] = df[col].fillna(median_val)\n",
    "                print(f\"Kolom '{col}': {missing_count} missing diisi dengan median ({median_val:.2f})\")\n",
    "            else:\n",
    "                modus_val = df[col].mode()[0]\n",
    "                df[col] = df[col].fillna(modus_val)\n",
    "                print(f\"Kolom '{col}': {missing_count} missing diisi dengan modus ({modus_val})\")\n",
    "\n",
    "    print(f\"\\nTotal {total_missing} missing values telah ditangani.\")\n",
    "    print(f\"Missing values setelah penanganan: {df.isnull().sum().sum()}\")\n",
    "else:\n",
    "    print(\"Tidak ada missing values. Dataset sudah lengkap.\")\n",
    "    print(\"Langkah ini tetap dipertahankan untuk mengantisipasi data baru di masa depan.\")\n",
    "\n",
    "# Export Intermediate CSV - Setelah Handling Missing Values\n",
    "df.to_csv('../data/processed/stunting_02_no_missing.csv', index=False)\n",
    "print(\"\\nIntermediate CSV tersimpan: data/processed/stunting_02_no_missing.csv\")\n",
    "print(f\"Shape: {df.shape[0]} baris, {df.shape[1]} kolom\")"
  ]},
  {"cell_type": "markdown", "metadata": {"tags": []}, "source": [
    "> **Kesimpulan Bagian 3:** Dataset stunting tidak memiliki missing values. Semua data lengkap dan siap untuk tahap selanjutnya.\n",
    "\n",
    "---\n",
    "# BAGIAN 4: OUTLIER DETECTION & HANDLING\n",
    "---"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# ============================================================\n",
    "# BAGIAN 4: OUTLIER DETECTION & HANDLING\n",
    "# Tujuan: Mendeteksi dan menangani outlier pada kolom numerik\n",
    "# ============================================================\n",
    "\n",
    "# 4.1 Statistik Deskriptif Detail\n",
    "numeric_cols = ['umur_bulan', 'tinggi']\n",
    "\n",
    "print(\"=== Statistik Deskriptif Kolom Numerik ===\")\n",
    "display(df[numeric_cols].describe().round(2))"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 4.2 Visualisasi Distribusi dan Outlier (Boxplot)\n",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
    "\n",
    "# Boxplot untuk umur_bulan\n",
    "sns.boxplot(y=df['umur_bulan'], ax=axes[0], color='skyblue')\n",
    "axes[0].set_title('Boxplot: Umur (Bulan)')\n",
    "axes[0].set_ylabel('Umur (Bulan)')\n",
    "\n",
    "# Boxplot untuk tinggi\n",
    "sns.boxplot(y=df['tinggi'], ax=axes[1], color='lightcoral')\n",
    "axes[1].set_title('Boxplot: Tinggi Badan (cm)')\n",
    "axes[1].set_ylabel('Tinggi (cm)')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Histogram dengan KDE\n",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
    "\n",
    "sns.histplot(df['umur_bulan'], kde=True, ax=axes[0], color='skyblue', bins=30)\n",
    "axes[0].set_title('Distribusi: Umur (Bulan)')\n",
    "axes[0].set_xlabel('Umur (Bulan)')\n",
    "\n",
    "sns.histplot(df['tinggi'], kde=True, ax=axes[1], color='lightcoral', bins=30)\n",
    "axes[1].set_title('Distribusi: Tinggi Badan (cm)')\n",
    "axes[1].set_xlabel('Tinggi (cm)')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 4.3 Deteksi Outlier dengan Metode IQR\n",
    "def detect_outliers_iqr(data, column):\n",
    "    \"\"\"\n",
    "    Deteksi outlier menggunakan metode Interquartile Range (IQR).\n",
    "    Rumus: Q1 - 1.5*IQR hingga Q3 + 1.5*IQR\n",
    "    \"\"\"\n",
    "    Q1 = data[column].quantile(0.25)\n",
    "    Q3 = data[column].quantile(0.75)\n",
    "    IQR = Q3 - Q1\n",
    "\n",
    "    lower_bound = Q1 - 1.5 * IQR\n",
    "    upper_bound = Q3 + 1.5 * IQR\n",
    "\n",
    "    outliers = data[(data[column] < lower_bound) | (data[column] > upper_bound)]\n",
    "\n",
    "    return {\n",
    "        'kolom': column,\n",
    "        'Q1': Q1,\n",
    "        'Q3': Q3,\n",
    "        'IQR': IQR,\n",
    "        'lower_bound': lower_bound,\n",
    "        'upper_bound': upper_bound,\n",
    "        'jumlah_outlier': len(outliers),\n",
    "        'persentase_outlier': round(len(outliers) / len(data) * 100, 2),\n",
    "        'outliers': outliers\n",
    "    }\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"DETEKSI OUTLIER DENGAN METODE IQR\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "for col in numeric_cols:\n",
    "    result = detect_outliers_iqr(df, col)\n",
    "    print(f\"\\n--- {col.upper()} ---\")\n",
    "    print(f\"  Q1 (25%): {result['Q1']:.2f}\")\n",
    "    print(f\"  Q3 (75%): {result['Q3']:.2f}\")\n",
    "    print(f\"  IQR: {result['IQR']:.2f}\")\n",
    "    print(f\"  Batas Bawah: {result['lower_bound']:.2f}\")\n",
    "    print(f\"  Batas Atas: {result['upper_bound']:.2f}\")\n",
    "    print(f\"  Jumlah Outlier: {result['jumlah_outlier']}\")\n",
    "    print(f\"  Persentase Outlier: {result['persentase_outlier']}%\")"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 4.4 Deteksi Outlier dengan Metode Z-Score\n",
    "try:\n",
    "    from scipy import stats\n",
    "    scipy_available = True\n",
    "except ImportError:\n",
    "    print(\"Library scipy belum terinstall. Menginstall sekarang...\")\n",
    "    import subprocess, sys\n",
    "    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'scipy'])\n",
    "    from scipy import stats\n",
    "    scipy_available = True\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"DETEKSI OUTLIER DENGAN METODE Z-SCORE\")\n",
    "print(\"=\" * 60)\n",
    "print(\"(Threshold: |Z-score| > 3 dianggap outlier)\")\n",
    "\n",
    "for col in numeric_cols:\n",
    "    z_scores = np.abs(stats.zscore(df[col]))\n",
    "    outlier_count = (z_scores > 3).sum()\n",
    "    outlier_pct = round(outlier_count / len(df) * 100, 2)\n",
    "    print(f\"\\n--- {col.upper()} ---\")\n",
    "    print(f\"  Jumlah Outlier (Z > 3): {outlier_count}\")\n",
    "    print(f\"  Persentase: {outlier_pct}%\")"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 4.5 Hubungan Umur vs Tinggi (Scatter Plot)\n",
    "plt.figure(figsize=(10, 6))\n",
    "\n",
    "# Warna berdasarkan status\n",
    "color_map = {'Normal': 'green', 'Stunted': 'orange', 'Severely Stunted': 'red'}\n",
    "colors = df['status'].map(color_map)\n",
    "\n",
    "scatter = plt.scatter(df['umur_bulan'], df['tinggi'], c=colors, alpha=0.6, edgecolors='black', linewidth=0.5)\n",
    "plt.xlabel('Umur (Bulan)')\n",
    "plt.ylabel('Tinggi Badan (cm)')\n",
    "plt.title('Hubungan Umur vs Tinggi Badan (Berdasarkan Status Stunting)')\n",
    "\n",
    "# Legend\n",
    "from matplotlib.patches import Patch\n",
    "legend_elements = [\n",
    "    Patch(facecolor='green', label='Normal'),\n",
    "    Patch(facecolor='orange', label='Stunted'),\n",
    "    Patch(facecolor='red', label='Severely Stunted')\n",
    "]\n",
    "plt.legend(handles=legend_elements, title='Status')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('../data/processed/scatter_umur_tinggi.png', dpi=100, bbox_inches='tight')\n",
    "plt.show()\n",
    "print(\"Visualisasi tersimpan: data/processed/scatter_umur_tinggi.png\")"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 4.6 Penanganan Outlier\n",
    "print(\"=\" * 60)\n",
    "print(\"PENANGANAN OUTLIER\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "# Strategi: Capping (Winsorization) - mengganti outlier dengan batas IQR\n",
    "# Alasan: Data tinggi dan umur anak memiliki variasi alami,\n",
    "# namun nilai ekstrim perlu dibatasi agar tidak mengganggu model\n",
    "\n",
    "df_clean = df.copy()\n",
    "total_capped = 0\n",
    "\n",
    "for col in numeric_cols:\n",
    "    Q1 = df_clean[col].quantile(0.25)\n",
    "    Q3 = df_clean[col].quantile(0.75)\n",
    "    IQR = Q3 - Q1\n",
    "    lower_bound = Q1 - 1.5 * IQR\n",
    "    upper_bound = Q3 + 1.5 * IQR\n",
    "\n",
    "    # Hitung outlier sebelum capping\n",
    "    before_outliers = ((df_clean[col] < lower_bound) | (df_clean[col] > upper_bound)).sum()\n",
    "\n",
    "    # Lakukan capping\n",
    "    df_clean[col] = df_clean[col].clip(lower=lower_bound, upper=upper_bound)\n",
    "\n",
    "    total_capped += before_outliers\n",
    "    print(f\"\\n--- {col.upper()} ---\")\n",
    "    print(f\"  Batas Bawah: {lower_bound:.2f}\")\n",
    "    print(f\"  Batas Atas: {upper_bound:.2f}\")\n",
    "    print(f\"  Outlier sebelum capping: {before_outliers}\")\n",
    "    print(f\"  Outlier setelah capping: {((df_clean[col] < lower_bound) | (df_clean[col] > upper_bound)).sum()}\")\n",
    "\n",
    "print(f\"\\nTotal outlier yang ditangani (capping): {total_capped}\")"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 4.7 Visualisasi Perbandingan Sebelum vs Sesudah Penanganan Outlier\n",
    "fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n",
    "\n",
    "for i, col in enumerate(numeric_cols):\n",
    "    # Sebelum\n",
    "    sns.boxplot(y=df[col], ax=axes[i, 0], color='lightcoral')\n",
    "    axes[i, 0].set_title(f'{col.upper()} - SEBELUM Penanganan Outlier')\n",
    "\n",
    "    # Sesudah\n",
    "    sns.boxplot(y=df_clean[col], ax=axes[i, 1], color='lightgreen')\n",
    "    axes[i, 1].set_title(f'{col.upper()} - SETELAH Penanganan Outlier')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('../data/processed/perbandingan_outlier.png', dpi=100, bbox_inches='tight')\n",
    "plt.show()\n",
    "print(\"Visualisasi tersimpan: data/processed/perbandingan_outlier.png\")"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 4.8 Export Intermediate CSV - Setelah Penanganan Outlier\n",
    "df_clean.to_csv('../data/processed/stunting_03_after_outlier.csv', index=False)\n",
    "print(\"Intermediate CSV tersimpan: data/processed/stunting_03_after_outlier.csv\")\n",
    "print(f\"Shape: {df_clean.shape[0]} baris, {df_clean.shape[1]} kolom\")"
  ]},
  {"cell_type": "markdown", "metadata": {"tags": []}, "source": [
    "> **Kesimpulan Bagian 4:** Outlier berhasil dideteksi menggunakan metode IQR dan Z-Score. Penanganan dilakukan dengan capping (winsorization) untuk mempertahankan jumlah data sambil mengurangi pengaruh nilai ekstrim.\n",
    "\n",
    "---\n",
    "# BAGIAN 5: EXPORT CLEAN DATASET & SUMMARY\n",
    "---"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# ============================================================\n",
    "# BAGIAN 5: EXPORT CLEAN DATASET & SUMMARY\n",
    "# Tujuan: Menyimpan dataset bersih dan merangkum hasil\n",
    "# ============================================================\n",
    "\n",
    "# 5.1 Simpan Dataset Bersih\n",
    "# Simpan dengan delimiter koma untuk kemudahan akses\n",
    "df_clean.to_csv('../data/processed/stunting_clean.csv', index=False)\n",
    "print(\"Dataset bersih tersimpan di: data/processed/stunting_clean.csv\")"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 5.2 Perbandingan Sebelum vs Sesudah Cleaning\n",
    "print(\"=\" * 60)\n",
    "print(\"PERBANDINGAN SEBELUM VS SESUDAH CLEANING\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "print(f\"\\n--- Dimensi Data ---\")\n",
    "print(f\"  Sebelum: {df_raw.shape[0]} baris, {df_raw.shape[1]} kolom\")\n",
    "print(f\"  Sesudah: {df_clean.shape[0]} baris, {df_clean.shape[1]} kolom\")\n",
    "\n",
    "print(f\"\\n--- Missing Values ---\")\n",
    "print(f\"  Sebelum: {df_raw.isnull().sum().sum()}\")\n",
    "print(f\"  Sesudah: {df_clean.isnull().sum().sum()}\")\n",
    "\n",
    "print(f\"\\n--- Tipe Data ---\")\n",
    "print(f\"  Sebelum:\")\n",
    "print(df_raw.dtypes)\n",
    "print(f\"\\n  Sesudah:\")\n",
    "print(df_clean.dtypes)\n",
    "\n",
    "print(f\"\\n--- 5 Data Pertama (Sesudah) ---\")\n",
    "display(df_clean.head())"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 5.3 Statistik Perbandingan Numerik\n",
    "print(\"=\" * 60)\n",
    "print(\"PERBANDINGAN STATISTIK NUMERIK\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "for col in numeric_cols:\n",
    "    print(f\"\\n--- {col.upper()} ---\")\n",
    "    comparison = pd.DataFrame({\n",
    "        'Sebelum': df[col].describe(),\n",
    "        'Sesudah': df_clean[col].describe()\n",
    "    }).round(2)\n",
    "    display(comparison)"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 5.4 Ringkasan Final\n",
    "print(\"=\" * 60)\n",
    "print(\"RINGKASAN FINAL CLEANING DATASET\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "data_dict = {\"raw_rows\": df_raw.shape[0], \"clean_rows\": df_clean.shape[0], \"cols\": df_clean.shape[1]}\n",
    "\n",
    "summary = f\"\"\"\n",
    "Dataset: stunting.csv\n",
    "Total Sampel Awal: {data_dict['raw_rows']}\n",
    "Total Sampel Akhir: {data_dict['clean_rows']}\n",
    "Jumlah Kolom: {data_dict['cols']}\n",
    "\n",
    "TAHAPAN YANG TELAH DILAKUKAN:\n",
    "1. Data Loading & Eksplorasi Awal\n",
    "2. Data Preprocessing:\n",
    "   - Standardisasi nama kolom\n",
    "   - Fix inkonsistensi nilai Status (spasi, kapitalisasi)\n",
    "   - Standardisasi kolom JK (L/P -> Laki-Laki/Perempuan)\n",
    "   - Deteksi dan hapus duplikasi data (22 duplikat dihapus)\n",
    "   - Konversi tipe data numerik\n",
    "\n",
    "3. Handling Missing Values:\n",
    "   - Tidak ditemukan missing values dalam dataset\n",
    "   - Handler tetap disiapkan untuk antisipasi data baru\n",
    "\n",
    "4. Outlier Detection & Handling:\n",
    "   - Metode IQR (Q1 - 1.5*IQR, Q3 + 1.5*IQR): 1 outlier di tinggi\n",
    "   - Metode Z-Score (|Z| > 3): 2 outlier di tinggi\n",
    "   - Penanganan: Capping/Winsorization\n",
    "\n",
    "5. Export Dataset Bersih ke CSV\n",
    "\"\"\"\n",
    "\n",
    "print(summary)\n",
    "\n",
    "# Simpan ringkasan ke file\n",
    "with open('../data/processed/ringkasan_cleaning.txt', 'w') as f:\n",
    "    f.write(summary)\n",
    "print(\"Ringkasan tersimpan di: data/processed/ringkasan_cleaning.txt\")"
  ]},
  {"cell_type": "code", "execution_count": None, "metadata": {"tags": []}, "outputs": [], "source": [
    "# 5.5 Verifikasi Data Bersih\n",
    "print(\"=\" * 60)\n",
    "print(\"VERIFIKASI AKHIR\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "# Load kembali dataset yang telah disimpan\n",
    "df_verified = pd.read_csv('../data/processed/stunting_clean.csv')\n",
    "\n",
    "print(f\"\\nDataset berhasil dimuat kembali: {df_verified.shape[0]} baris, {df_verified.shape[1]} kolom\")\n",
    "print(f\"\\n=== Cek Missing Values ===\")\n",
    "print(df_verified.isnull().sum())\n",
    "\n",
    "print(f\"\\n=== Cek Duplikasi ===\")\n",
    "print(f\"Jumlah duplikat: {df_verified.duplicated().sum()}\")\n",
    "\n",
    "print(f\"\\n=== Distribusi Status ===\")\n",
    "print(df_verified['status'].value_counts())\n",
    "\n",
    "print(\"\\nDataset STUNTING_CLEAN.csv siap digunakan untuk pemodelan!\")"
  ]},
  {"cell_type": "markdown", "metadata": {"tags": []}, "source": [
    "---\n",
    "## Kesimpulan Akhir\n",
    "\n",
    "Proses **Data Cleaning** pada dataset stunting telah selesai dilakukan dengan tahapan:\n",
    "\n",
    "| Tahap | Keterangan | Status |\n",
    "|-------|-----------|--------|\n",
    "| 1 | Setup & Data Loading | Selesai |\n",
    "| 2 | Data Preprocessing | Selesai |\n",
    "| 3 | Handling Missing Values | Selesai |\n",
    "| 4 | Outlier Detection & Handling | Selesai |\n",
    "| 5 | Export Clean Dataset | Selesai |\n",
    "\n",
    "**Hasil Akhir:** Dataset bersih tersimpan di data/processed/stunting_clean.csv\n",
    "\n",
    "---\n",
    "*Notebook ini dibuat untuk proyek penelitian prediksi stunting pada balita.*"
  ]}
 ],
 "metadata": {
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
  "language_info": {"name": "python", "version": "3.10.0"}
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open('notebooks/penelitian.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print('Notebook created successfully!')
md = sum(1 for c in nb['cells'] if c['cell_type'] == 'markdown')
cd = sum(1 for c in nb['cells'] if c['cell_type'] == 'code')
cells_count = len(nb['cells'])
print(f'Cells: {cells_count} total ({md} markdown + {cd} code)')
